(async () => {
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const check = (ok, message) => { if (!ok) throw new Error(message); };
  const type = text => { const el = document.querySelector('#campo-msg'); el.value = text; el.dispatchEvent(new Event('input', { bubbles: true })); return el; };
  const first = type('Olá, posso ajudar sua empresa.');
  first.focus(); first.setSelectionRange(5, 8);
  await wait(6200);
  check(document.querySelector('#campo-msg') === first, 'Editor foi recriado');
  check(first.value === 'Olá, posso ajudar sua empresa.', 'Rascunho apagado');
  check(document.activeElement === first && first.selectionStart === 5 && first.selectionEnd === 8, 'Foco ou seleção perdido');
  const trans = document.querySelector('.transcricao'); trans.scrollTop = 0;
  await wait(5500);
  check(document.querySelector('.transcricao').scrollTop === 0, 'Rolagem alterada');
  document.querySelector('#btn-enviar').click();
  await wait(100);
  check(document.querySelector('#btn-enviar').disabled, 'Envio duplicado permitido');
  document.querySelectorAll('.item')[1].click();
  await wait(500);
  type('Rascunho do Rafael');
  await wait(7500);
  check(document.querySelector('#campo-msg').value === 'Rascunho do Rafael', 'Envio apagou rascunho de outro contato');
  document.querySelectorAll('.item')[0].click();
  await wait(500);
  check(document.querySelector('#campo-msg').value === '', 'Rascunho enviado não foi limpo');
  check(document.querySelectorAll('.humano').length === 1, 'Envio ausente ou duplicado');
  type('falhar'); document.querySelector('#btn-enviar').click();
  await wait(7500);
  check(document.querySelector('#campo-msg').value === 'falhar', 'Falha perdeu rascunho');
  check(document.querySelector('#erro-envio').textContent.includes('Falha simulada'), 'Erro não exibido');
  check(!document.querySelector('#btn-enviar').disabled, 'Envio bloqueado após falha');
  document.querySelector('#btn-pausa').click(); await wait(700);
  check(document.querySelector('#btn-pausa').textContent.includes('Devolver'), 'Pausa falhou');
  document.querySelector('#btn-pausa').click(); await wait(700);
  check(document.querySelector('#btn-pausa').textContent.includes('Assumir'), 'Retomada falhou');
  check(document.querySelector('#campo-msg').getBoundingClientRect().bottom <= innerHeight, 'Editor fora da tela');
  return 'PASS: polling, foco, seleção, rolagem, rascunhos por contato, envio, falha, pausa e retomada.';
})();
